#:schema https://mise.jdx.dev/schema/mise.json

[tools]
flyctl = "latest"
node = "24"

# astro
[tasks.build]
run = "npm run build"

[tasks.dev]
run = "npm run dev"

# caddy
[tasks."caddy:build"]
run = "docker build --target=caddy-builder -t caddy-builder ."
[tasks."caddy:fmt"]
depends = ["caddy:build"]
run = [
  "docker run -it --rm -v ./Caddyfile:/tmp/Caddyfile caddy-builder caddy fmt --overwrite --config /tmp/Caddyfile",
]
[tasks."caddy:lint"]
depends = ["caddy:build"]
run = [
  "docker build --target=caddy-builder -t caddy-builder .",
  "docker run -it --rm -v ./Caddyfile:/tmp/Caddyfile caddy-builder caddy validate --config /tmp/Caddyfile",
]

# docker
[tasks."docker:build"]
run = "docker build -t bonkydev ."

[tasks."docker:dev"]
run = [
  "docker build -t bonkydev .",
  "docker run -it --rm -p 8080:8080 bonkydev",
]

# working with fly
[tasks.deploy]
run = "fly deploy"

[tasks.logs]
run = "fly logs"
