#:schema https://mise.jdx.dev/schema/mise.json

[tools]
flyctl = "latest"

# web deploy
[tasks."web:deploy"]
dir = "web"
run = "fly deploy"

[tasks."web:logs"]
dir = "web"
run = "fly logs"

[tasks."ntfy:deploy"]
dir = "ntfy"
run = "fly deploy"

[tasks."ntfy:logs"]
dir = "ntfy"
run = "fly logs"

[tasks."idp:deploy"]
dir = "idp"
run = "fly deploy"

[tasks."idp:logs"]
dir = "idp"
run = "fly logs"
